### ISSUE TITLE
按照这种规则下去，估计所有的公司都有污点

### ISSUE THREAD

**Issue by robinv8** [ShameCom/ShameCom#10]

**Comment by heroims** [comment]
非常对，当所有公司都在其内，就毫无意义，还不如考虑一下为什么别人没遇到。。。。。

**Comment by robinv8** [comment]
@ShameCom 建议设置写规则，不能什么都收集，这样会误导学弟学妹

**Comment by robinv8** [comment]
@ShameCom 有些公司确实有些不恰当的行为，但也不能以这种方式误导学弟学妹，诋毁一家公司，那些帖子只是单方面说了公司的问题，但基本上没提到个人的问题，如果真是为了学弟学妹，应该提一下努力、踏实、好学的重要性。

**Comment by stackOverflowHidden** [comment]
> 非常对，当所有公司都在其内，就毫无意义，还不如考虑一下为什么别人没遇到。。。。。

车祸遇难者也应该反思下为什么那天自己出门上马路是吧，犹太人也应该反思下自己为什么被无辜关进集中营是吧
