### ISSUE TITLE
同学，要多考虑自身问题

### ISSUE THREAD

**Issue by maolion** [ShameCom/ShameCom#13]
“胜者为王，。。。。” 是大公司也得考虑养人成本 要养 也得养对的人

**Comment by WadeStack** [comment]
社达主义虽迟但到

**Comment by WadeStack** [comment]
社达主义虽迟但到 @maolion

**Comment by Lilysunstrider** [comment]
> “胜者为王，。。。。” 是大公司也得考虑养人成本 要养 也得养对的人

你背叛了工人阶级，(  )(  )(  )

**Comment by ylink-lfs** [comment]
做个人吧

**Comment by stackOverflowHidden** [comment]
不想培养别招啊，发意向书毁了算什么。
让受害者考虑自身问题，你咋不考虑下你自身有没有脑子🧠呢？菜逼loser
