### ISSUE TITLE
建议用web.archive.org来代替长截图

### ISSUE THREAD

**Issue by zionfuo** [ShameCom/ShameCom#19]
保存地址：http://web.archive.org/save

**Comment by xiantang** [comment]
能不能把这些脑瘫公司刻在区块链上啊 这样就永远不会被抹除

**Comment by Dragon1573** [comment]
@xiantang 能不能打区块链上还很难说，或许可以让 @ShameCom 为此仓库开启 GitHub Arctic Code Vault 计划，争取下一次归档计划把这些记录冰封在北极冰盖之下？

这样一说好像也不错
