### ISSUE TITLE
你好，在牛客看到一个“西山居欺骗实习生的帖子”

### ISSUE THREAD

**Issue by zhweiGuo** [ShameCom/ShameCom#22]
[链接](https://www.nowcoder.com/discuss/554535)

**Comment by zhweiGuo** [comment]
为了防止帖子被公关掉，我先把截图放在这里，当事人来了可以让我删除。
![www nowcoder com_discuss_554535](https://user-images.githubusercontent.com/15942478/97779703-c7823b80-1bba-11eb-9dc4-2d8679281b8e.png)

**Comment by zhweiGuo** [comment]
再加一个58转转毁应届生意向书的帖子：[链接](https://www.nowcoder.com/discuss/554654)，图片备份：

![www nowcoder com_discuss_554654](https://user-images.githubusercontent.com/15942478/97780969-0fa55c00-1bc3-11eb-9302-5168565263b7.png)

**Comment by CN-GuoZiyang** [comment]
老哥可以试着发个PR
