### ISSUE TITLE
为啥毁oc的不算污点

### ISSUE THREAD

**Issue by KyrieXu11** [ShameCom/ShameCom#29]
有无好心人解答一下

**Comment by ShameCom** [comment]
OC通常属于HR个人行为，而意向书是需要向校招组申请才可发放，可代表公司

**Comment by anti715** [comment]
> OC通常属于HR个人行为，而意向书是需要向校招组申请才可发放，可代表公司

我有些不同的看法，有些HR本身就是执行着企业的意志，同时HR本身的存在就代表着企业，同时当遭遇到这种问题时，求职的人不可能绕过HR去找企业维权。所以OC本身也应该算污点才对。只有记录了，企业才会关注到，并追责恶意个人行为的HR

**Comment by Z-fly** [comment]
> > OC通常属于HR个人行为，而意向书是需要向校招组申请才可发放，可代表公司
> 
> 我有些不同的看法，有些HR本身就是执行着企业的意志，同时HR本身的存在就代表着企业，同时当遭遇到这种问题时，求职的人不可能绕过HR去找企业维权。所以OC本身也应该算污点才对。只有记录了，企业才会关注到，并追责恶意个人行为的HR
> 所以这种行为如果不记录，让毕业生自己去怼HR，反而更有可能让HR有借口在企业间流通的HR黑名单上把毕业生拉黑。这样毕业的更难找工作了。
> 所以不论是HR的行为还是企业的行为，都应该一概归类成企业污点。
> 仅仅是个人想法。

不懂就问，OC是啥意思？

**Comment by anti715** [comment]
> > > OC通常属于HR个人行为，而意向书是需要向校招组申请才可发放，可代表公司
> > 
> > 
> > 我有些不同的看法，有些HR本身就是执行着企业的意志，同时HR本身的存在就代表着企业，同时当遭遇到这种问题时，求职的人不可能绕过HR去找企业维权。所以OC本身也应该算污点才对。只有记录了，企业才会关注到，并追责恶意个人行为的HR
> > 所以这种行为如果不记录，让毕业生自己去怼HR，反而更有可能让HR有借口在企业间流通的HR黑名单上把毕业生拉黑。这样毕业的更难找工作了。
> > 所以不论是HR的行为还是企业的行为，都应该一概归类成企业污点。
> > 仅仅是个人想法。
> 
> 不懂就问，OC是啥意思？

HC
“HC 充足，欢迎来撩”。

HC 指的就是 Head Count，俗称人头数，这里指的是招聘名额。

JD
“JD 如下，有意者联系”。

JD（Job Description），工作职责描述，也就是企业的一些要求。例如招聘后端研发，一般会要求你熟悉 Java/Golang 等等。

OC
“终于 OC 了！”。

OC （Offer Call），当企业决定录用你时，会打电话发 Offer，并询问你是否接受。一般 OC 也称为「开奖」。

BU/BG
BG（Business Group），事业群。例如腾讯公司为人熟知的微信事业群（WeiXin Group，简称WXG）和互动娱乐事业群（Interactive Entertainment Group，简称IEG）。

BU（Business Unit），通常指业务线或者产品线，是 BG 下的细分的业务或者产品。





还有一些和岗位强相关的，这里也整理一下，在工作中经常听到。
PR
PR（Public Relationship），公共关系，即平时说的公关，一般在传媒、互联网、品牌营销各种行业会出现。主要的工作范围就是舆情监测，客户管理，媒体关系，文案输出，活动策划等等。

PD
PD（Product Designer），产品设计或产品负责人。目前的工作中经常需要和 PD 打交道。

PM
PM（Product Manager/Project Manager）：产品经理或项目经理。在产品的研发过程中，PM 会负责调查并根据用户的需求，确定开发何种产品, 选择何种技术、商业模式等。
