### ISSUE TITLE
截图工具相关问题

### ISSUE THREAD

**Issue by dc932dc** [ShameCom/ShameCom#61]
您好，请问您的截图工具是什么

**Comment by JasonGrass** [comment]
README 里面有写 

如何使用网页长截图留档
使用 Chrome 浏览器 59 或更高版本chrome://settings/help
进入待截图的网页
按下 F12 快捷键（或鼠标右键 >> 审查元素），调出 Web 开发者工具
按下 Ctrl + Shift + P 快捷键，调出指令执行界面
输入 Capture full size screenshot（支持模糊搜索）指令（该指令中文环境下为“捕获全尺寸屏幕截图”），点击或回车

**Comment by JasonGrass** [comment]
这个 chrome 插件也可以：
https://chrome.google.com/webstore/detail/awesome-screenshot-screen/nlipoenfbbikpbjkfpfillcgkoblgpmj 
[Awesome Screenshot -- Screen recorder and Screen capture](https://www.awesomescreenshot.com/ )

**Comment by dc932dc** [comment]
> 这个铬插件也可以： [Https://chrome.google.com/webstore/detail/awesome-screenshot-screen/nlipoenfbbikpbjkfpfillcgkoblgpmj](https://chrome.google.com/webstore/detail/awesome-screenshot-screen/nlipoenfbbikpbjkfpfillcgkoblgpmj) [令人敬畏的屏幕截图-屏幕记录器和屏幕截图](https://www.awesomescreenshot.com/)

好的，感谢您的回答
